name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (API)
        working-directory: apps/api
        run: npm install

      - name: Initialize database
        working-directory: apps/api
        run: npm run db:init

      - name: Start API
        working-directory: apps/api
        run: npm run dev &

      - name: Install dependencies (Web)
        working-directory: apps/web
        run: npm install

      - name: Start Web Server
        working-directory: apps/web
        run: npm run dev &

      - name: Wait for services to be ready
        run: sleep 5

      - name: Install dependencies for Tests
        run: npm install

      - name: install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        env:
          BASE_URL: http://localhost:8080
          BASE_API: http://localhost:3333
        run: npx playwright test

      - name: Publish HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
